name: petal_talk
description: "PetalTalk - A beautiful Flarum community client."
# 以下行防止包被意外发布到pub.dev，使用`flutter pub publish`命令。这对于私有包来说是首选的。
publish_to: "none" # 如果你想发布到pub.dev，请删除这一行

# 以下定义了应用程序的版本和构建号。
# 版本号是由点分隔的三个数字，如1.2.43
# 后面可以跟一个由+分隔的可选构建号。
# 在Flutter构建中，可以分别通过指定--build-name和--build-number来覆盖版本和构建号。
# 在Android中，build-name用作versionName，而build-number用作versionCode。
# 有关Android版本控制的更多信息，请访问https://developer.android.com/studio/publish/versioning
# 在iOS中，build-name用作CFBundleShortVersionString，而build-number用作CFBundleVersion。
# 有关iOS版本控制的更多信息，请访问
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# 在Windows中，build-name用作产品版本和文件版本的主要、次要和补丁部分，
# 而build-number用作构建后缀。
version: 0.0.10+001010

environment:
  sdk: ^3.10.4

# 依赖项指定了你的包工作所需的其他包。
# 要自动将包依赖项升级到最新版本，
# 请考虑运行`flutter pub upgrade --major-versions`。或者，
# 可以通过将下面的版本号更改为pub.dev上可用的最新版本来手动更新依赖项。
# 要查看哪些依赖项有可用的新版本，请运行`flutter pub outdated`。
dependencies:
  flutter:
    sdk: flutter

  # 以下将Cupertino Icons字体添加到您的应用程序中。
  # 与CupertinoIcons类一起使用，用于iOS风格的图标。
  cupertino_icons: ^1.0.8
  get: ^4.6.5
  # 日志库
  logger: ^2.0.2

  # html解析
  html: ^0.15.4
  # html渲染
  flutter_html: ^3.0.0-beta.2
  # 文本语法高亮
  re_highlight: ^0.0.3
  # 展开/收起
  expandable: ^5.0.1
  # 高帧率
  flutter_displaymode: ^0.7.0
  # 浏览器
  webview_flutter: ^4.8.0

  # 解决sliver滑动不同步
  extended_nested_scroll_view: ^6.2.1
  # 上拉加载
  loading_more_list: ^7.1.0
  # 下拉刷新
  pull_to_refresh_notification: ^3.0.1

  # toast
  flutter_smart_dialog: ^4.9.4
  # 下滑关闭
  dismissible_page: ^1.0.2
  custom_sliding_segmented_control: ^1.8.3
  # 权限
  permission_handler: ^12.0.1
  # 动态取色
  dynamic_color: ^1.7.0
  # 文件路径
  path_provider: ^2.1.2
  # GUID生成
  flutter_guid: ^0.3.1

  # 网络
  dio: ^5.4.1
  cookie_jar: ^4.0.8
  dio_cookie_manager: ^3.1.1
  connectivity_plus: ^7.0.0
  dio_http2_adapter: ^2.3.1+1
  # 本地存储
  shared_preferences: ^2.2.3
  # 链接打开
  url_launcher: ^6.2.5
  # 自定义窗口标题栏
  window_manager: ^0.5.1

  # M3E 组件库
  m3e_collection: ^0.3.7
  webview_windows: ^0.4.0
  # 推送通知
  flutter_local_notifications: ^19.5.0
  # 通知权限处理
  flutter_native_timezone: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # 下面的"flutter_lints"包包含了一组推荐的lints，
  # 用于鼓励良好的编码实践。该包提供的lint集在位于您的包根目录的
  # `analysis_options.yaml`文件中激活。有关禁用特定lint规则和激活其他规则的信息，
  # 请参阅该文件。
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

# 有关此文件的通用Dart部分的信息，请参阅以下页面：https://dart.dev/tools/pub/pubspec

# 以下部分特定于Flutter包。
flutter:
  # 以下行确保Material Icons字体包含在您的应用程序中，
  # 以便您可以在material Icons类中使用这些图标。
  uses-material-design: true

  # 资源目录
  assets:
    - assets/
    - LICENSE
    - assets/icons/
    - assets/icons/logo.png

  # 图片资源可以引用一个或多个特定分辨率的"变体"，请参阅
  # https://flutter.dev/to/resolution-aware-images

  # 有关从包依赖项添加资源的详细信息，请参阅
  # https://flutter.dev/to/asset-from-package

  # 要向应用程序添加自定义字体，请在此处的"flutter"部分添加一个fonts部分。
  # 此列表中的每个条目都应包含一个带有字体系列名称的"family"键，以及一个带有
  # 字体资产和其他描述符列表的"fonts"键。例如：
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # 有关包依赖项字体的详细信息，
  # 请参阅https://flutter.dev/to/font-from-package
# 应用图标配置
flutter_launcher_icons:
  # 为 Android 配置图标
  android: true
  # 为 iOS 配置图标
  ios: true
  # 指定图标图片路径
  image_path: "assets/icons/logo.png"
